/*
 * This file is part of Baritone.
 *
 * Baritone is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Baritone is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Baritone.  If not, see <https://www.gnu.org/licenses/>.
 */

plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.17'
    id 'maven-publish'
}

base {
    archivesName = "${archives_base_name}-fabric"
}

version = mod_version
group = maven_group

java {
    sourceCompatibility = JavaVersion.toVersion(java_version)
    targetCompatibility = sourceCompatibility

    toolchain {
        languageVersion.set(JavaLanguageVersion.of(sourceCompatibility.majorVersion.toInteger()))
    }

    withSourcesJar()
}

repositories {
    mavenCentral()
    maven {
        name = 'babbaj-repo'
        url = 'https://babbaj.github.io/maven/'
    }
}

sourceSets {
    main {
        java.srcDirs += ['src/api/java', 'src/launch/java']
        resources.srcDir 'src/launch/resources'
    }
    schematica_api {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
    main {
        compileClasspath += schematica_api.output
        runtimeClasspath += schematica_api.output
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_version}"

    implementation "dev.babbaj:nether-pathfinder:${nether_pathfinder_version}"
    include "dev.babbaj:nether-pathfinder:${nether_pathfinder_version}"
    implementation 'com.google.code.findbugs:jsr305:3.0.2'

    testImplementation 'junit:junit:4.13.2'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = java_version.toInteger()
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

javadoc {
    options.addStringOption('Xwerror', '-quiet')
    options.linkSource true
    options.encoding 'UTF-8'
    source = fileTree('src/api/java')
    classpath += sourceSets.main.compileClasspath
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId 'meteordevelopment'
            artifactId 'baritone'
            from components.java
        }
    }

    repositories {
        maven {
            name = 'meteor-maven'
            url = 'https://maven.meteordev.org/snapshots'
            credentials {
                username = System.getenv('MAVEN_METEOR_ALIAS')
                password = System.getenv('MAVEN_METEOR_TOKEN')
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
